### PR TITLE
Fixed bug 13 by handling consonants only

### PR DESCRIPTION
**Pull request by mrejster**

### CODE REVIEW

**Comment by victor-fors** [comment]
Is a exit of the program motivated over ignoring words?

**Comment by oneyoke** [comment]
@mrejster Have you thought about "by", "dry" and other cases with "y" as a vowel?

**Comment by mrejster** [comment]
That's a freakishly difficult issue! It will not be implemented, and is more of a general error of the English language.

**Comment by victor-fors** [comment]
I disagree, this is extremely important!

**Comment by oneyoke** [comment]
Let's fix it under assumption that "y" together with a vowel is a consonant.

**Pull request merged**
